spring.application.name=backend-api
spring.config.import=optional:file:.env[.properties]
server.port=8082
# Configuração do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/minimarket_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


